/**************************************************************************
 *                                                                        *
 *  Catapult(R) MatchLib Toolkit Example Design Library                   *
 *                                                                        *
 *  Software Version: 1.2                                                 *
 *                                                                        *
 *  Release Date    : Fri Jan 28 15:14:12 PST 2022                        *
 *  Release Type    : Production Release                                  *
 *  Release Build   : 1.2.7                                               *
 *                                                                        *
 *  Unpublished work. Copyright 2020 Siemens                              *
 *                                                                        *
 **************************************************************************/

// This document contains information that is proprietary to Siemens
// The original recipient of this document may duplicate this  
// document in whole or in part for internal business purposes only, provided  
// that this entire notice appears in all copies. In duplicating any part of  
// this document, the recipient agrees to make every reasonable effort to  
// prevent the unauthorized use and distribution of the proprietary information.

// Autogenerated from wrapper_gen.py on Mon, 07 Dec 2020 21:49:27 +0000
// Arguments: Namespace(clock_name='clk', clock_period='10', exec_args=None, exec_name='../08_dma/sim_sc', header=None, not_top_level=None, obj_name='top.dma1', start_clk_low=None)

#include "dma_wrap.h"

sc_trace_file* trace_file_ptr;

#ifdef SC_MODULE_EXPORT
SC_MODULE_EXPORT(dma_wrap);
#endif
