// INSERT_EULA_COPYRIGHT: 2020

// Autogenerated from wrapper_gen.py on Mon, 07 Dec 2020 21:49:27 +0000
// Arguments: Namespace(clock_name='clk', clock_period='10', exec_args=None, exec_name='../08_dma/sim_sc', header=None, not_top_level=None, obj_name='top.dma1', start_clk_low=None)

#include "dma_wrap.h"

sc_trace_file* trace_file_ptr;

#ifdef SC_MODULE_EXPORT
SC_MODULE_EXPORT(dma_wrap);
#endif
