// INSERT_EULA_COPYRIGHT: 2020
// Autogenerated from wrapper_gen.py on Mon, 07 Dec 2020 21:53:04 +0000
// Arguments: Namespace(clock_name='clk', clock_period='10', exec_args=None, exec_name='../08_dma/sim_sc', header=None, not_top_level='true', obj_name='top.ram1', start_clk_low=None)

#include "ram_wrap.h"


#ifdef SC_MODULE_EXPORT
SC_MODULE_EXPORT(ram_wrap);
#endif
